### ISSUE TITLE
After wallet connects, still shows "Please connect an Ethereum wallet to your browser to use the application"

### ISSUE THREAD

**Issue by jlucasmcrell** [Ben-Haslam/uniswap-deploy-scripts#1]
After wallet connects, still shows "Please connect an Ethereum wallet to your browser to use the application" on page, does not refresh to swap page.

![uniswap](https://user-images.githubusercontent.com/105783305/169075029-6de436fc-1983-4561-9a73-d95738590651.png)

**Comment by Ben-Haslam** [comment]
As this interface is an experimental work in progress, I deliberately dropped support for eth mainnet, which is why it doesnt work. LMK if you think it would be a good idea to add mainnet back. Also looks like you put this issue on the wrong repo

**Comment by jlucasmcrell** [comment]
Hi Ben,

Yes, I would like the ETH Mainnet back, I think it would be a great idea...
honestly I'd expect that would be the main reason anyone would look for a
Uniswap script, no?

Thanks!
Joe

**Comment by Ben-Haslam** [comment]
Have added mainnet support back in and a bunch of default tokens
